/**
* dauthwallet
* 账号注册，登录，授权接口
*
* OpenAPI spec version: v1.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.infras.dauthsdk.login.model

/**
 * Bind phone param
 *
 * @property openudid
 * @property phone
 * @property phone_area_code
 * @property verify_code
 * @property sign
 * @property accessTokenInHeader
 * @constructor Create empty Bind phone param
 */
data class BindPhoneParam (
    /* 用户id */
    val openudid: String,
    /* 手机号 */
    val phone: String,
    /* 手机区号 */
    val phone_area_code: String,
    /* 验证码 */
    val verify_code: String,
    /* 检验参数 */
    val sign: String,
    val accessTokenInHeader: AccessTokenInHeader? = null
)

