/**
* dauthwallet
* 账号注册，登录，授权接口
*
* OpenAPI spec version: v1.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.infras.dauthsdk.login.model

import com.infras.dauthsdk.login.network.BaseResponse
import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass


/**
 * 
 * @param session_id 用户登录凭证
 */

@JsonClass(generateAdapter = true)
data class LoginRes(val data: Data? = null) : BaseResponse() {
    @JsonClass(generateAdapter = true)
    class Data {
        /* 用户登录凭证 */
        @Json(name = "did_token") var didToken: String? = null
    }
}

