/**
* dauthwallet
* 账号注册，登录，授权接口
*
* OpenAPI spec version: v1.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.infras.dauthsdk.login.model

import com.infras.dauthsdk.login.network.BaseResponse
import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass


/**
 * 
 * @param openudid 用户id
 * @param access_token 用户登录标识,调用凭证,接口header传入,有效期短
 * @param expire_in access_token有效期，单位（秒）
 * @param refresh_token 用于刷新access_token,每次刷新返回新的
 */

@JsonClass(generateAdapter = true)
data class RefreshTokenParamRes (
   val data: Data?
) : BaseResponse() {
    @JsonClass(generateAdapter = true)
    class Data {
        /* 用户id */
        @Json(name = "openudid") var openId: String? = null

        /* 用户登录标识,调用凭证,接口header传入,有效期短 */
        @Json(name = "access_token") var accessToken: String? = null

        /* access_token有效期，单位（秒） */
        @Json(name = "expire_in") var expireIn: Long? = null

        /* 用于刷新access_token,每次刷新返回新的 */
        @Json(name = "refresh_token") var refreshToken: String? = null
    }
}

