/**
* dauthwallet
* 账号注册，登录，授权接口
*
* OpenAPI spec version: v1.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.cyberflow.dauthsdk.login.model


/**
 * 
 * @param  
 * @param account 用户账号
 * @param phone_area_code 手机号登录时必填
 * @param password 密码
 * @param client 客户端 web\\apple\\android
 * @param user_type 登录来源
 * @param sign 检验参数
 */
data class AuthByPasswordParam (
    /* 用户账号 */
    val account: String,
    /* 密码 */
    val password: String,
    /* 客户端 web\\apple\\android */
    val client: String,
    /* 登录来源 */
    val user_type: Int,
    /* 检验参数 */
    val sign: String,
    val clientInHeader: ClientInHeader? = null,
    /* 手机号登录时必填 */
    val phone_area_code: String? = null
) {

}

