/**
* dauthwallet
* 账号注册，登录，授权接口
*
* OpenAPI spec version: v1.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.cyberflow.dauthsdk.login.model

/**
 * 
 * @param  
 * @param openudid 用户id
 * @param user_type 登录来源
 */
data class GetAcccountInfoParam (
    /* 用户id */
    val openudid: String,
    /* 登录来源 */
    val user_type: Int,
     val accessTokenInHeader: AccessTokenInHeader? = null
) {

}

