/**
* dauthwallet
* 账号注册，登录，授权接口
*
* OpenAPI spec version: v1.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.cyberflow.dauthsdk.login.model

import com.cyberflow.dauthsdk.login.network.BaseResponse


/**
 * 
 * @param session_id 用户登录凭证
 */
data class LoginRes (
    /* 用户登录凭证 */
    val session_id: String,
    val data: Data
) : BaseResponse(){
    class Data{
        var did_token: String ?= null
    }
}

