@startuml
'https://plantuml.com/activity-diagram-beta
skin rose

start

if (钱包初始化完成) then (Y)
    end
else (N)
endif

if (钱包正在初始化) then (Y)
else (N)
    if (恢复可用) then (Y)
        :恢复流程;
        end
    else (N)
    endif
endif
:创建钱包;

end

@enduml
