/**
* dauthwallet
* 账号注册，登录，授权接口
*
* OpenAPI spec version: v1.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.cyberflow.dauthsdk.login.model


/**
 * 
 * @param account 用户账号
 * @param nickname 用户昵称
 * @param birthday 用户生日
 * @param sex 性别 0保密 1男 2女
 * @param email 邮箱
 * @param phone_area_code 电话区号
 * @param phone 电话号码
 * @param real_name 用户真实名称
 * @param identity 身份证
 * @param identity_Status 
 * @param head_img_url 用户图像地址
 * @param country 国家/地区
 * @param province 省份
 * @param city 城市
 * @param district 区
 * @param address 详细地址
 * @param user_type 注册来源
 * @param user_state 用户状态
 * @param create_time 注册时间
 */


data class Account(
    val account: String,
    val nickname: String,
    val birthday: String,
    val sex: Int,
    val email: String,
    val phone_area_code: String,
    val phone: Long,
    val identity_Status: Int,
    val head_img_url: String,
    val country: String,
    val province: String,
    val city: String,
    val district: String,
    val address: String,
    val user_type: Int,
    val user_state: Int,
    val create_time: String,
    val real_name: String? = null,
    val identity: String? = null
) {

}

