/**
* dauthwallet
* 账号注册，登录，授权接口
*
* OpenAPI spec version: v1.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.cyberflow.dauthsdk.login.model

import com.cyberflow.dauthsdk.login.network.BaseResponse
import kotlinx.serialization.Contextual
import kotlinx.serialization.Serializable


/**
 * 
 * @param did_token id_token
 * @param token_expire DIDToken过期时间
 * @param refresh_after DIDToken应该刷新的时间 一般过期时间的前几天
 */

@Serializable
data class AuthorizeToken2Res(
    var data: @Contextual Data? = null
) : BaseResponse() {
    @Serializable
    class Data {
        val did_token: String? = null
        val d_access_token: String? = null
        val d_refresh_token: String? = null
        val d_expire_in: Long? = null
    }
}

