/**
 * dauthwallet
 * 账号注册，登录，授权接口
 *
 * OpenAPI spec version: v1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.cyberflow.dauthsdk.login.model


/**
 *
 * @param account 邮箱
 * @param verify_code 验证码
 * @param app_id 所属应用id
 */
data class AuthByEmailVCode(
    /* 邮箱 */
    val account: String,
    /* 验证码 */
    val verify_code: Int,
    /* 所属应用id */
    val app_id: Int
) {

}

