/**
* dauthwallet
* 账号注册，登录，授权接口
*
* OpenAPI spec version: v1.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.cyberflow.dauthsdk.login.model

import com.cyberflow.dauthsdk.login.network.BaseResponse
import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass


/**
 * 
 * @param did_token id_token
 * @param token_expire DIDToken过期时间
 * @param refresh_after DIDToken应该刷新的时间 一般过期时间的前几天
 */

@JsonClass(generateAdapter = true)
data class AuthorizeToken2Res(
    @Json(name = "data") val data: Data?
) : BaseResponse() {
    @JsonClass(generateAdapter = true)
    class Data {
        @Json(name = "did_token") var didToken: String? = null
        @Json(name = "d_access_token") var accessToken: String? = null
        @Json(name = "d_refresh_token") var refreshToken: String? = null
        @Json(name = "d_expire_in") var expireIn: Long? = null
    }
}

