/**
* dauthwallet
* 账号注册，登录，授权接口
*
* OpenAPI spec version: v1.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.cyberflow.dauthsdk.login.model


/**
 * 
 * @param  
 * @param openudid 用户id
 * @param nickname 昵称
 * @param birthday 生日
 * @param sex 性别 0保密 1男 2女
 * @param head_img_url 用户图像地址
 * @param country 国家/地区
 * @param province 省份
 * @param city 城市
 * @param district 区
 * @param address 详细地址
 * @param sign 检验参数
 */

data class BindRealInfoParam (
    /* 用户id */
    val openudid: String,
    /* 昵称 */
    val nickname: String,
    /* 生日 */
    val birthday: String,
    /* 性别 0保密 1男 2女 */
    val sex: Int,
    /* 用户图像地址 */
    val head_img_url: String,
    /* 国家/地区 */
    val country: String,
    /* 省份 */
    val province: String,
    /* 城市 */
    val city: String,
    /* 区 */
    val district: String,
    /* 详细地址 */
    val address: String,
    /* 检验参数 */
    val sign: String,
    val accessTokenInHeader: AccessTokenInHeader? = null
) {

}

