/**
* dauthwallet
* 账号注册，登录，授权接口
*
* OpenAPI spec version: v1.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.cyberflow.dauthsdk.login.model

/**
 * 
 * @param  
 * @param openudid 用户id
 * @param account 邮箱
 * @param verify_code 验证码
 * @param sign 检验参数
 */
data class BindEmailParam (
    /* 授权id */
    val authid: String,
    /* 邮箱 */
    val account: String,
    /* 验证码 */
    val verify_code: String,
    var access_token: String,
    /* 检验参数 */
    val sign: String? = null,
    val accessTokenInHeader : AccessTokenInHeader? = null
) {

}

