/**
* dauthwallet
* 账号注册，登录，授权接口
*
* OpenAPI spec version: v1.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.cyberflow.dauthsdk.login.model

import com.squareup.moshi.JsonClass


/**
 * 
 * @param account 用户账号
 * @param nickname 用户昵称
 * @param birthday 用户生日
 * @param sex 性别 0保密 1男 2女
 * @param email 邮箱
 * @param phone_area_code 电话区号
 * @param phone 电话号码
 * @param real_name 用户真实名称
 * @param identity 身份证
 * @param identity_Status 
 * @param head_img_url 用户图像地址
 * @param country 国家/地区
 * @param province 省份
 * @param city 城市
 * @param district 区
 * @param address 详细地址
 * @param user_type 注册来源
 * @param user_state 用户状态
 * @param create_time 注册时间
 */

@JsonClass(generateAdapter = true)
data class GetAcccountInfoRes (
    /* 用户账号 */
    val account: String,
    /* 用户昵称 */
    val nickname: String,
    /* 用户生日 */
    val birthday: String,
    /* 性别 0保密 1男 2女 */
    val sex: Int,
    /* 邮箱 */
    val email: String,
    /* 电话区号 */
    val phone_area_code: String,
    /* 电话号码 */
    val phone: Long,
    val identity_Status: Int,
    /* 用户图像地址 */
    val head_img_url: String,
    /* 国家/地区 */
    val country: String,
    /* 省份 */
    val province: String,
    /* 城市 */
    val city: String,
    /* 区 */
    val district: String,
    /* 详细地址 */
    val address: String,
    /* 注册来源 */
    val user_type: Int,
    /* 用户状态 */
    val user_state: Int,
    /* 注册时间 */
    val create_time: String,
    /* 用户真实名称 */
    val real_name: String? = null,
    /* 身份证 */
    val identity: String? = null
) {

}

