/**
* dauthwallet
* 账号注册，登录，授权接口
*
* OpenAPI spec version: v1.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.cyberflow.dauthsdk.login.model

import com.cyberflow.dauthsdk.login.network.BaseResponse
import kotlinx.serialization.Contextual
import kotlinx.serialization.Serializable


/**
 * 
 * @param session_id 用户登录凭证
 */

@Serializable
data class LoginRes (val data: Data) : BaseResponse() {
    @Serializable
    class Data {
        /* 用户登录凭证 */
        val did_token: String? = null
    }
}

