/**
* dauthwallet
* 账号注册，登录，授权接口
*
* OpenAPI spec version: v1.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.cyberflow.dauthsdk.login.model

/**
 * 
 * @param  
 * @param email 邮箱
 */
data class QueryByEMailParam (
    /* 邮箱 */
    val email: String,
    var access_token: String,
    val authid: String,
    val accessTokenInHeader: AccessTokenInHeader? = null
) {

}

