/**
* dauthwallet
* 账号注册，登录，授权接口
*
* OpenAPI spec version: v1.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.cyberflow.dauthsdk.login.model

import com.cyberflow.dauthsdk.login.network.BaseResponse


/**
 * 
 * @param openudid 用户id
 * @param access_token 用户登录标识,调用凭证,接口header传入,有效期短
 * @param expire_in access_token有效期，单位（秒）
 * @param refresh_token 用于刷新access_token,每次刷新返回新的
 */
data class RefreshTokenParamRes (
   val data: Data?
) : BaseResponse() {
    class Data {
        /* 用户id */
        val openudid: String? = null

        /* 用户登录标识,调用凭证,接口header传入,有效期短 */
        val access_token: String? = null

        /* access_token有效期，单位（秒） */
        var expire_in: Long? = null

        /* 用于刷新access_token,每次刷新返回新的 */
        val refresh_token: String? = null
    }
}

