/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cyberflow_dauthsdk_mpc_DAuthJni */

#ifndef _Included_com_cyberflow_dauthsdk_mpc_DAuthJni
#define _Included_com_cyberflow_dauthsdk_mpc_DAuthJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cyberflow_dauthsdk_mpc_DAuthJni
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_cyberflow_dauthsdk_mpc_DAuthJni_init
        (JNIEnv *, jobject);

/*
 * Class:     com_cyberflow_dauthsdk_mpc_DAuthJni
 * Method:    generateSignKeys
 * Signature: (II)I
 */
JNIEXPORT jobjectArray JNICALL Java_com_cyberflow_dauthsdk_mpc_DAuthJni_generateSignKeys
        (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_cyberflow_dauthsdk_mpc_DAuthJni
 * Method:    refreshKeys
 * Signature: ([Ljava/lang/String;I)I
 */
JNIEXPORT jobjectArray JNICALL Java_com_cyberflow_dauthsdk_mpc_DAuthJni_refreshKeys
        (JNIEnv *, jobject, jobjectArray, jint);

/*
 * Class:     com_cyberflow_dauthsdk_mpc_DAuthJni
 * Method:    localSignMsg
 * Signature: (Ljava/lang/String;[Ljava/lang/String;[Ljava/lang/Integer;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_cyberflow_dauthsdk_mpc_DAuthJni_localSignMsg
        (JNIEnv *, jobject, jstring, jobjectArray, jintArray);

/*
 * Class:     com_cyberflow_dauthsdk_mpc_DAuthJni
 * Method:    remoteSignMsg
 * Signature: (Ljava/lang/String;Ljava/lang/String;I[Ljava/lang/Integer;[C)J
 */
JNIEXPORT jlong JNICALL Java_com_cyberflow_dauthsdk_mpc_DAuthJni_remoteSignMsg
        (JNIEnv *, jobject, jstring, jstring, jint, jintArray, jobject);

/*
 * Class:     com_cyberflow_dauthsdk_mpc_DAuthJni
 * Method:    remoteSignRound
 * Signature: (JI[C[B)Z
 */
JNIEXPORT jboolean JNICALL Java_com_cyberflow_dauthsdk_mpc_DAuthJni_remoteSignRound
        (JNIEnv *, jobject, jlong, jint, jbyteArray, jobject);

#ifdef __cplusplus
}
#endif
#endif
