/**
* dauthwallet
* 账号注册，登录，授权接口
*
* OpenAPI spec version: v1.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.cyberflow.dauthsdk.model


/**
 * 
 * @param did_token id_token
 * @param token_expire DIDToken过期时间
 * @param refresh_after DIDToken应该刷新的时间 一般过期时间的前几天
 */
data class AuthorizeToken2Res(
    val did_token: kotlin.String,
    val d_access_token: kotlin.String,
    val d_refresh_token: kotlin.String,
    val d_expire_in: kotlin.Long
) {

}

