/**
 * dauthwallet
 * 账号注册，登录，授权接口
 *
 * OpenAPI spec version: v1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.cyberflow.dauthsdk.model


/**
 *
 * @param openudid 用户id
 * @param app_id 所属应用id
 * @param token token
 */
data class AuthenticatonParam(
    /* 用户id */
    val openudid: String,
    /* 所属应用id */
    val app_id: Int,
    /* token */
    val token: String
) {

}

