/**
* dauthwallet
* 账号注册，登录，授权接口
*
* OpenAPI spec version: v1.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.cyberflow.dauthsdk.model


/**
 * 
 * @param code 用户id
 */
data class AuthByEmailVCodeRes (
    /* 用户id */
    val code: String
) {

}

