/**
* dauthwallet
* 账号注册，登录，授权接口
*
* OpenAPI spec version: v1.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.cyberflow.dauthsdk.model

import com.cyberflow.dauthsdk.model.AccessTokenInHeader

/**
 * 
 * @param  
 * @param openudid 用户main openudid
 * @param subaccesscode sub账号的access code
 * @param user_type 账号类型
 * @param sign 检验参数
 */
data class BindAcoountParam (
    /* 用户main openudid */
    val openudid: kotlin.String,
    /* sub账号的access code */
    val subaccesscode: kotlin.String,
    /* 账号类型 */
    val user_type: kotlin.Int,
    /* 检验参数 */
    val sign: kotlin.String,
    val accessTokenInHeader : AccessTokenInHeader? = null
) {

}

