/**
* dauthwallet
* 账号注册，登录，授权接口
*
* OpenAPI spec version: v1.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.cyberflow.dauthsdk.model

import com.cyberflow.dauthsdk.model.AccessTokenInHeader

/**
 * 
 * @param  
 * @param openudid 用户id
 * @param nickname 昵称
 * @param birthday 生日
 * @param sex 性别 0保密 1男 2女
 * @param head_img_url 用户图像地址
 * @param country 国家/地区
 * @param province 省份
 * @param city 城市
 * @param district 区
 * @param address 详细地址
 * @param sign 检验参数
 */
data class BindRealInfoParam (
    /* 用户id */
    val openudid: kotlin.String,
    /* 昵称 */
    val nickname: kotlin.String,
    /* 生日 */
    val birthday: kotlin.String,
    /* 性别 0保密 1男 2女 */
    val sex: kotlin.Int,
    /* 用户图像地址 */
    val head_img_url: kotlin.String,
    /* 国家/地区 */
    val country: kotlin.String,
    /* 省份 */
    val province: kotlin.String,
    /* 城市 */
    val city: kotlin.String,
    /* 区 */
    val district: kotlin.String,
    /* 详细地址 */
    val address: kotlin.String,
    /* 检验参数 */
    val sign: kotlin.String,
     val accessTokenInHeader: AccessTokenInHeader? = null
) {

}

