/**
* dauthwallet
* 账号注册，登录，授权接口
*
* OpenAPI spec version: v1.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.cyberflow.dauthsdk.model


/**
 * 
 * @param ClientID 所属应用id
 * @param Platform 客户端 web\\apple\\android
 */
data class CommonHeader (
    /* 所属应用id */
    val ClientID: kotlin.String? = null,
    /* 客户端 web\\apple\\android */
    val Platform: kotlin.String? = null
) {

}

