/**
* dauthwallet
* 账号注册，登录，授权接口
*
* OpenAPI spec version: v1.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.cyberflow.dauthsdk.model

 

/**
 * 
 * @param  
 * @param user_type 账号类型 :10邮箱注册,20钱包注册,30谷歌,40facebook,50苹果,60手机号,70自定义帐号,80一键注册,100Discord,110Twitter
 * @param phone 手机号,手机号登录时必填
 * @param phone_area_code 手机区号,手机号登录时必填
 * @param account 邮箱账号或自定义账号,账号登录时必填
 * @param password 密码,账号登录时必填
 * @param verify_code 验证码,手机号或邮箱登录时必填
 * @param sign 检验参数
 */
data class LoginParam(
    /* 账号类型 */
    val user_type: Int,
    /* 检验参数 */
    val sign: String,
    val clientInHeader: ClientInHeader? = null,
    /* 手机号,手机号登录时必填 */
    val phone: String? = null,
    /* 手机区号,手机号登录时必填 */
    val phone_area_code: String? = null,
    /* 邮箱账号或自定义账号,账号登录时必填 */
    val account: String? = null,
    /* 密码,账号登录时必填 */
    val password: String? = null,
    /* 验证码,手机号或邮箱登录时必填 */
    val verify_code: String? = null
) {

}

