/**
* dauthwallet
* 账号注册，登录，授权接口
*
* OpenAPI spec version: v1.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.cyberflow.dauthsdk.model

 

/**
 * 
 * @param  
 * @param user_type 账号类型
 * @param platform 客户端 web\\apple\\android
 * @param session_id 用户登录凭证
 * @param sign 检验参数
 */
data class LoginAuthParam (
    /* 账号类型 */
    val user_type: kotlin.Int,
    /* 客户端 web\\apple\\android */
    val platform: kotlin.String,
    /* 用户登录凭证 */
    val session_id: kotlin.String,
    /* 检验参数 */
    val sign: kotlin.String,
    val clientInHeader: ClientInHeader? = null
) {

}

